apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
spec:
  interval: 1h
  chart:
    spec:
      chart: teleport-cluster
      version: "18.3.2"
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: teleport-cluster
      interval: 1h
  values:
    clusterName: teleport.example.com
    proxyListenerMode: multiplex
    acme: false
    acmeEmail: santoaaron@gmail.com
